# Generated by Django 3.1.1 on 2020-11-06 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0002_subdivision_leader'),
        ('users', '0002_auto_20201106_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
    ]
