# Generated by Django 3.1.3 on 2020-11-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subdivisions', '0002_subdivision_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Начальник', to=settings.AUTH_USER_MODEL, verbose_name='Лидер'),
        ),
    ]
