# Generated by Django 3.1.3 on 2020-11-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0003_auto_20201106_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
