# Generated by Django 3.1.3 on 2020-11-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0004_auto_20201106_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_title', models.CharField(max_length=64, verbose_name='Подрядная организация')),
            ],
            options={
                'verbose_name': 'Подрядная организация',
                'verbose_name_plural': 'Подрядные организациия',
            },
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='asui_code',
            new_name='subdivision_asui_code',
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='ekasui_title',
            new_name='subdivision_ekasui_title',
        ),
        migrations.RenameField(
            model_name='subdivision',
            old_name='leader',
            new_name='subdivision_leader',
        ),
    ]
