# Generated by Django 3.1.3 on 2020-11-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0005_auto_20201109_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
