# Generated by Django 3.1.3 on 2020-12-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_theme', models.CharField(max_length=64, verbose_name='Тема сообщения')),
                ('feedback_message', models.TextField(verbose_name='Сообщение')),
                ('feedback_state', models.BooleanField(verbose_name='Состояние')),
                ('feedback_pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('feedback_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Контактное лицо')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
