# Generated by Django 3.1.4 on 2020-12-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_state',
            field=models.BooleanField(verbose_name='Выполнено'),
        ),
    ]
