# Generated by Django 3.1.3 on 2020-12-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='KipDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kip_device_type', models.CharField(max_length=32, verbose_name='Тип/Марка')),
                ('kip_device_number', models.IntegerField(verbose_name='Заводской номер')),
                ('kip_device_calibration_date', models.DateField(verbose_name='Дата калибровки')),
                ('kip_device_name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('kip_device_pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('kip_device_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Измерительный прибор',
                'verbose_name_plural': 'Измерительные приборы',
            },
        ),
    ]
