# Generated by Django 3.1.1 on 2020-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_title', models.CharField(max_length=128, verbose_name='наименование организации')),
                ('short_title', models.CharField(max_length=16, verbose_name='Короткое название организациия')),
                ('asui_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='Код АСУИ')),
            ],
        ),
    ]
