# Generated by Django 3.1.3 on 2020-11-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20201106_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_title', models.CharField(max_length=64, verbose_name='Подрядная организация')),
            ],
            options={
                'verbose_name': 'Подрядная организация',
                'verbose_name_plural': 'Подрядные организациия',
            },
        ),
    ]
