# Generated by Django 3.1.3 on 2020-11-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20201109_1404'),
        ('feeds', '0003_auto_20201106_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_file',
            field=models.ManyToManyField(blank=True, to='files.File'),
        ),
    ]
