# Generated by Django 3.1.3 on 2020-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20201109_1404'),
        ('feeds', '0004_feed_feed_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.AddField(
            model_name='feed',
            name='feed_tags',
            field=models.ManyToManyField(blank=True, to='feeds.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feed_file',
            field=models.ManyToManyField(blank=True, to='files.File', verbose_name='Прикрепленные файлы'),
        ),
    ]
