# Generated by Django 3.1.3 on 2020-12-15 15:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_auto_20201109_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_text',
            field=tinymce.models.HTMLField(null=True, verbose_name='Содержание новости'),
        ),
    ]
