# Generated by Django 3.1.3 on 2020-11-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dga', '0001_initial'),
        ('organizations', '0003_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=64, verbose_name='Навазние станции')),
                ('station_type', models.CharField(choices=[(1, 'Станция'), (2, 'Перегон')], max_length=16, verbose_name='Станция|Перегон')),
                ('station_dga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dga.dgalist', verbose_name='Тип ДГА')),
                ('station_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Организация')),
            ],
        ),
    ]
