# Generated by Django 3.1.3 on 2020-11-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0006_delete_contractor'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция|Перегон', 'verbose_name_plural': 'Станции|Перегоны'},
        ),
        migrations.AddField(
            model_name='station',
            name='station_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
    ]
