# Generated by Django 3.1.3 on 2020-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=128, verbose_name='Наименование файла')),
                ('file_name', models.FileField(blank=True, null=True, upload_to='test/%Y/%M/%D/', verbose_name='Файл')),
            ],
        ),
    ]
