# Generated by Django 3.1.3 on 2020-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201107_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='test/%Y/%m/%D/', verbose_name='Файл'),
        ),
    ]
