# Generated by Django 3.1.3 on 2020-11-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_remove_folder_organization'),
        ('files', '0006_auto_20201107_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder', verbose_name='Папка в которой распологается файл'),
        ),
    ]
