# Generated by Django 3.1.3 on 2020-11-07 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_file_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_folder',
        ),
    ]
