# Generated by Django 3.1.3 on 2020-11-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_remove_file_file_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
