# Generated by Django 3.1.3 on 2020-11-08 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0011_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=128, verbose_name='Наименование файла')),
                ('file_name', models.FileField(blank=True, null=True, upload_to=files.models.upload_to, verbose_name='Файл')),
                ('file_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Автор файла')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файл',
            },
        ),
    ]
