# Generated by Django 3.1.3 on 2020-11-09 06:04

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0010_auto_20201108_1056'),
        ('files', '0013_file_file_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_folder',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder', verbose_name='Папка в которой распологается файл'),
        ),
    ]
