# Generated by Django 3.1.3 on 2020-11-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20201109_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
