# Generated by Django 3.1.3 on 2020-11-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_auto_20201106_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_class_text', models.CharField(max_length=128, verbose_name='Тип транспортного средства по классификатору')),
            ],
        ),
        migrations.CreateModel(
            name='AutomobileFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_fuel_text', models.CharField(max_length=128, verbose_name='Вид топлива')),
            ],
        ),
        migrations.CreateModel(
            name='AutomobileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_type_text', models.CharField(max_length=32, verbose_name='Тип транспортного средства')),
            ],
        ),
        migrations.CreateModel(
            name='Automobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automobile_model', models.CharField(max_length=32, verbose_name='Марка автомобиля')),
                ('automobile_number', models.CharField(max_length=9, verbose_name='Гос номер')),
                ('automobile_date_of_inspection', models.DateTimeField(auto_now_add=True, verbose_name='Дата осмотра')),
                ('automobile_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automobiles.automobileclass', verbose_name='Тип транспортного средства по классификатору')),
                ('automobile_fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automobiles.automobilefuel', verbose_name='Вид топлива')),
                ('automobile_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Организация')),
                ('automobile_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automobiles.automobiletype', verbose_name='Тип транспортного средства')),
            ],
        ),
    ]
