# Generated by Django 3.1.3 on 2020-11-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobile',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='automobileclass',
            options={'verbose_name': 'Классификация', 'verbose_name_plural': 'Классификации'},
        ),
        migrations.AlterModelOptions(
            name='automobilefuel',
            options={'verbose_name': 'Вид топлива', 'verbose_name_plural': 'Вид топлива'},
        ),
        migrations.AlterModelOptions(
            name='automobiletype',
            options={'verbose_name': 'Вид транспорта', 'verbose_name_plural': 'Виды транспорта'},
        ),
        migrations.AlterField(
            model_name='automobile',
            name='automobile_number',
            field=models.CharField(max_length=9, unique=True, verbose_name='Гос номер'),
        ),
    ]
