# Generated by Django 3.1.3 on 2020-11-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automobiles', '0004_automobilerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilerequest',
            name='automobile_request_executor',
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
