# Generated by Django 3.1.3 on 2020-11-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automobiles', '0005_auto_20201109_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_executor',
            field=models.ForeignKey(limit_choices_to=models.Q(groups__name='Электромеханики'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
