# Generated by Django 3.1.3 on 2020-11-09 14:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subdivisions', '0004_auto_20201106_2359'),
        ('automobiles', '0006_automobilerequest_automobile_request_executor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilerequest',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявка'},
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_agreed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Согласовано'),
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата прибытия'),
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_date_of_travel',
            field=models.DateTimeField(null=True, verbose_name='Дата поездки'),
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_odometer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Одометр'),
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 22, 8, 7, 650579), verbose_name='Дата формирования заявки'),
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Дата возвращения'),
        ),
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_executor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='Водители'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
