# Generated by Django 3.1.3 on 2020-11-09 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0008_auto_20201109_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilerequest',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 9, 23, 1, 14, 805524), verbose_name='Дата формирования заявки'),
        ),
    ]
