# Generated by Django 3.1.3 on 2020-11-11 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0016_auto_20201111_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 17, 8, 50, 9048), verbose_name='Дата формирования заявки'),
        ),
    ]
