# Generated by Django 3.1.3 on 2020-11-11 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0017_auto_20201111_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 17, 11, 16, 679496), verbose_name='Дата формирования заявки'),
        ),
    ]
