# Generated by Django 3.1.3 on 2020-11-12 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0019_auto_20201112_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 22, 19, 48, 293722), verbose_name='Дата формирования заявки'),
        ),
    ]
