# Generated by Django 3.1.3 on 2020-11-12 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0020_auto_20201112_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 22, 32, 23, 800096), verbose_name='Дата формирования заявки'),
        ),
    ]
