# Generated by Django 3.1.3 on 2020-11-12 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0022_auto_20201112_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 22, 55, 38, 348345), verbose_name='Дата формирования заявки'),
        ),
    ]
