# Generated by Django 3.1.3 on 2020-11-12 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0030_auto_20201112_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 23, 27, 25, 700254), verbose_name='Дата формирования заявки'),
        ),
    ]
