# Generated by Django 3.1.3 on 2020-11-12 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0031_auto_20201112_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 23, 38, 26, 32981), verbose_name='Дата формирования заявки'),
        ),
    ]
