# Generated by Django 3.1.3 on 2020-11-13 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0033_auto_20201112_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 19, 3, 10, 155209), verbose_name='Дата формирования заявки'),
        ),
    ]
