# Generated by Django 3.1.3 on 2020-11-19 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0035_auto_20201119_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 22, 2, 39, 333457), verbose_name='Дата формирования заявки'),
        ),
    ]
