# Generated by Django 3.1.3 on 2020-11-19 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0037_auto_20201119_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 0, 1, 52, 532812), verbose_name='Дата формирования заявки'),
        ),
    ]
