# Generated by Django 3.1.3 on 2020-11-21 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0038_auto_20201120_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 21, 49, 19, 185201), verbose_name='Дата формирования заявки'),
        ),
    ]
