# Generated by Django 3.1.3 on 2020-11-21 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0042_auto_20201121_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 23, 28, 17, 204471), verbose_name='Дата формирования заявки'),
        ),
    ]
