# Generated by Django 3.1.3 on 2020-11-24 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0043_auto_20201121_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 24, 21, 16, 53, 942363), verbose_name='Дата формирования заявки'),
        ),
    ]
