# Generated by Django 3.1.3 on 2020-11-25 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0046_auto_20201124_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 16, 30, 16, 256893), verbose_name='Дата формирования заявки'),
        ),
    ]
