# Generated by Django 3.1.3 on 2020-11-25 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0047_auto_20201125_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 16, 32, 15, 109829), verbose_name='Дата формирования заявки'),
        ),
    ]
