# Generated by Django 3.1.3 on 2020-11-26 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0048_auto_20201125_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 0, 49, 39, 480488), verbose_name='Дата формирования заявки'),
        ),
    ]
