# Generated by Django 3.1.3 on 2020-11-30 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0050_auto_20201127_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 30, 23, 20, 55, 610588), verbose_name='Дата формирования заявки'),
        ),
    ]
