# Generated by Django 3.1.3 on 2020-11-30 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0051_auto_20201130_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 1, 1, 8, 123035), verbose_name='Дата формирования заявки'),
        ),
    ]
