# Generated by Django 3.1.3 on 2020-12-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0053_auto_20201210_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 23, 21, 44, 234773), verbose_name='Дата формирования заявки'),
        ),
    ]
