# Generated by Django 3.1.3 on 2020-12-16 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0062_auto_20201216_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 23, 33, 22, 830402), verbose_name='Дата формирования заявки'),
        ),
    ]
