# Generated by Django 3.1.3 on 2020-12-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0063_auto_20201216_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 0, 10, 4, 250961), verbose_name='Дата формирования заявки'),
        ),
    ]
