# Generated by Django 3.1.4 on 2020-12-24 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0064_auto_20201217_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilerequest',
            name='automobile_request_automobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automobiles.automobile', verbose_name='Автотранспорт'),
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 0, 45, 41, 798731), verbose_name='Дата формирования заявки'),
        ),
    ]
