# Generated by Django 3.1.4 on 2021-02-09 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0065_auto_20201225_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время прибытия'),
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 23, 53, 56, 760624), verbose_name='Дата формирования заявки'),
        ),
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время возвращения'),
        ),
    ]
