# Generated by Django 3.1.4 on 2021-02-18 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0067_auto_20210216_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 21, 7, 20, 502521), verbose_name='Дата формирования заявки'),
        ),
    ]
