# Generated by Django 3.1.4 on 2021-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0069_auto_20210218_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_date_of_travel',
            field=models.DateField(null=True, verbose_name='Дата поездки'),
        ),
    ]
