# Generated by Django 3.1.4 on 2021-02-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0070_auto_20210218_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilerequest',
            name='automobile_request_put_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата формирования заявки'),
        ),
    ]
