# Generated by Django 3.1.3 on 2020-11-10 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_contractor'),
        ('subdivisions', '0006_delete_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_contractor_date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('journal_contractor_date_finish', models.DateTimeField(verbose_name='Дата завершения')),
                ('journal_contractor_notice', models.CharField(max_length=128, verbose_name='Предупреждение')),
                ('journal_contractor_ppr', models.CharField(max_length=128, verbose_name='ППР')),
                ('journal_contractor_certificate_of_admission', models.CharField(max_length=128, verbose_name='Акт-допуск')),
                ('journal_contractor_admission_to_work', models.CharField(max_length=128, verbose_name='Наряд допуск')),
                ('journal_contractor_cable_inspection_document', models.CharField(max_length=128, verbose_name='Акт проверки трассы кабелей')),
                ('journal_contractor_cable_responsible_executor', models.CharField(max_length=128, verbose_name='Ответственный исполнитель')),
                ('journal_contractor_cable_responsible_manager', models.CharField(max_length=128, verbose_name='Ответственный руководитель')),
                ('journal_contractor_cable_date_and_number_of_order', models.CharField(max_length=128, verbose_name='№ и дата приказа')),
                ('journal_contractor_nature_of_work', models.CharField(max_length=128, verbose_name='Характер выполняемых работ')),
                ('journal_contractor_project_title', models.CharField(max_length=128, verbose_name='Титул проекта')),
                ('journal_contractor_contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.contractor', verbose_name='Подряная организация')),
                ('journal_contractor_responsible_user_for_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отвественный по ШЧ')),
                ('journal_contractor_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Место проведения работ')),
            ],
            options={
                'verbose_name': 'Работа подрядных организаций',
                'verbose_name_plural': 'Работа подрядной организации',
            },
        ),
    ]
