# Generated by Django 3.1.3 on 2020-11-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_auto_20201110_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalcontractor',
            options={'verbose_name': 'Работа подрядной организации', 'verbose_name_plural': 'Работа подрядных организаций'},
        ),
    ]
