# Generated by Django 3.1.3 on 2020-11-10 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subdivisions', '0006_delete_contractor'),
        ('journals', '0004_auto_20201110_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_notice_date_plan', models.DateTimeField(verbose_name='Дата выполенния работ')),
                ('journal_notice_time_start', models.TimeField(verbose_name='Начальное время по МСК')),
                ('journal_notice_time_end', models.TimeField(verbose_name='Конечное время по МСК')),
                ('journal_notice_description', models.TextField(verbose_name='Описание')),
                ('journal_notice_place', models.CharField(max_length=128, verbose_name='Место работ (№ пути, километр, пикет)')),
                ('journal_notice_date_of_entry_in_arm_lp', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время внесения в АРМ-ЛП по МСК')),
                ('journal_notice_number_acceptance', models.IntegerField(unique=True, verbose_name='Номер принятия')),
                ('journal_notice_fact_delivery_date', models.DateTimeField(auto_now_add=True, verbose_name='Время фактического конца работ')),
                ('journal_notice_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('journal_notice_create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('journal_notice_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Место на предупреждение')),
                ('journal_notice_translate_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь передавший в АРМ-"ЛП"')),
            ],
            options={
                'verbose_name': 'Предупреждение на производство работы',
                'verbose_name_plural': 'Предупрежденя на производство работ',
            },
        ),
    ]
