# Generated by Django 3.1.3 on 2020-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_journalnotice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalnotice',
            options={'verbose_name': 'Предупреждение на производство работы', 'verbose_name_plural': 'Предупреждения на производство работ'},
        ),
        migrations.AlterField(
            model_name='journalnotice',
            name='journal_notice_date_plan',
            field=models.DateField(verbose_name='Дата выполенния работ'),
        ),
        migrations.AlterField(
            model_name='journalnotice',
            name='journal_notice_number_acceptance',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Номер принятия'),
        ),
    ]
