# Generated by Django 3.1.3 on 2020-11-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subdivisions', '0006_delete_contractor'),
        ('journals', '0006_auto_20201111_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_work_title', models.CharField(max_length=128, unique=True, verbose_name='Наименование работ')),
            ],
            options={
                'verbose_name': 'Наименование работы',
                'verbose_name_plural': 'Наименования работ',
            },
        ),
        migrations.CreateModel(
            name='JournalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_order_number', models.IntegerField(unique=True, verbose_name='Номер разрешения')),
                ('journal_order_description', models.TextField(verbose_name='Примечание заявки')),
                ('journal_order_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('journal_order_datetime_on', models.DateTimeField(verbose_name='Дата и время включения')),
                ('journal_order_datetime_off', models.DateTimeField(verbose_name='Дата и время включения')),
                ('journal_order_allow_user', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='Выдача приказов'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рашрешен ШЧ')),
                ('journal_order_leader_user', models.ForeignKey(limit_choices_to=models.Q(groups__name='ШНС'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответ ШН|ШНС')),
                ('journal_order_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение')),
                ('journal_order_type_of_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.typeofwork', verbose_name='Наименовние работ')),
            ],
        ),
    ]
