# Generated by Django 3.1.3 on 2020-11-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_auto_20201112_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalorderobject',
            name='journal_order_object_journal_order_turning_off',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journals.journalorderturningoff', verbose_name='Включенный объект'),
        ),
    ]
