# Generated by Django 3.1.3 on 2020-11-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_journalorderobject_journal_order_object_journal_order_turning_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalorderobject',
            name='journal_order_object_journal_order_turning_off',
        ),
    ]
