# Generated by Django 3.1.3 on 2020-11-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subdivisions', '0006_delete_contractor'),
        ('journals', '0017_auto_20201112_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmperageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amperage_type_title', models.CharField(max_length=128, verbose_name='Питание')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEMSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_emsu_date_setup', models.DateField(verbose_name='Дата установки')),
                ('journal_emsu_switch_number', models.IntegerField(verbose_name='Номер стрелки')),
                ('journal_emsu_engine_number', models.IntegerField(verbose_name='Номер двигателя ЭМСУ')),
                ('journal_emsu_date_create', models.DateField(verbose_name='Год выпуска двигателя ЭМСУ')),
                ('journal_emsu_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикациизаписи')),
            ],
            options={
                'verbose_name': 'Учет вигателей ЭМСУ',
                'verbose_name_plural': 'Учет двигателя ЭМСУ',
            },
        ),
        migrations.CreateModel(
            name='JournalOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_order_object_application_note', models.TextField(verbose_name='Примечание заявки')),
                ('journal_order_turning_off_permit_number', models.IntegerField(unique=True, verbose_name='Номер выключения')),
                ('journal_order_turning_off_datetime_off', models.DateTimeField(verbose_name='Дата и время выключения')),
                ('journal_order_turning_off_allowed_ds', models.CharField(blank=True, max_length=128, null=True, verbose_name='Расшешено ДС')),
                ('journal_order_turning_on_inclusion_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер включения')),
                ('journal_order_object_on_datetime_on', models.DateTimeField(verbose_name='Дата и время включения')),
                ('journal_order_turning_on_description', models.TextField(blank=True, null=True, verbose_name='Примечание к включению')),
                ('journal_order_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('journal_order_object_on_responsible_shchd_user_on', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name=['ШЧД', 'ШЧДС']), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отвественный ШЧД/ШЧДС при включении')),
                ('journal_order_object_on_responsible_shns_user_on', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name=['ШН', 'ШНС']), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный ШН/ШНС при включении')),
                ('journal_order_object_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение')),
                ('journal_order_object_type_of_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.typeofwork', verbose_name='Наименовние работ')),
                ('journal_order_turning_off_allow_shch_user', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name='ШЧ'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Разрешено ШЧ')),
                ('journal_order_turning_off_responsible_shchd_user_off', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name=['ШЧД', 'ШЧДС']), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отвественный ШЧД/ШЧДС при выключении')),
                ('journal_order_turning_off_responsible_shns_user_off', models.ForeignKey(blank=True, limit_choices_to=models.Q(groups__name=['ШН', 'ШНС']), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный ШН/ШНС при выключении')),
            ],
            options={
                'verbose_name': 'Приказы на включение и выклчюение устройств',
                'verbose_name_plural': 'Приказ на включение и выклчюение устройства',
            },
        ),
        migrations.RemoveField(
            model_name='journalorderturningoff',
            name='journal_order_turning_off_responsible_shchd_user_off',
        ),
        migrations.RemoveField(
            model_name='journalorderturningoff',
            name='journal_order_turning_off_responsible_shns_user_off',
        ),
        migrations.RemoveField(
            model_name='journalorderturningon',
            name='journal_order_turning_on_allow_shch_user',
        ),
        migrations.RemoveField(
            model_name='journalorderturningon',
            name='journal_order_turning_on_responsible_shchd_user_on',
        ),
        migrations.RemoveField(
            model_name='journalorderturningon',
            name='journal_order_turning_on_responsible_shns_user_on',
        ),
        migrations.DeleteModel(
            name='JournalOrderObject',
        ),
        migrations.DeleteModel(
            name='JournalOrderTurningOff',
        ),
        migrations.DeleteModel(
            name='JournalOrderTurningOn',
        ),
    ]
