# Generated by Django 3.1.3 on 2020-11-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0018_auto_20201119_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalorder',
            options={'verbose_name': 'Приказ на включение и выключение устройства', 'verbose_name_plural': 'Приказы на включение и выключение устройств'},
        ),
        migrations.AlterField(
            model_name='journalorder',
            name='journal_order_object_on_datetime_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время включения'),
        ),
        migrations.AlterField(
            model_name='journalorder',
            name='journal_order_turning_off_datetime_off',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выключения'),
        ),
    ]
