# Generated by Django 3.1.3 on 2020-11-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subdivisions', '0006_delete_contractor'),
        ('journals', '0019_auto_20201119_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalorder',
            name='journal_order_object_on_responsible_shchd_user_on',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'ШЧД'), ('groups__name', 'ШЧДC'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отвественный ШЧД/ШЧДС при включении'),
        ),
        migrations.AlterField(
            model_name='journalorder',
            name='journal_order_object_on_responsible_shns_user_on',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'ШН'), ('groups__name', 'ШНС'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный ШН/ШНС при включении'),
        ),
        migrations.AlterField(
            model_name='journalorder',
            name='journal_order_turning_off_responsible_shchd_user_off',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'ШЧД'), ('groups__name', 'ШЧДC'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отвественный ШЧД/ШЧДС при выключении'),
        ),
        migrations.AlterField(
            model_name='journalorder',
            name='journal_order_turning_off_responsible_shns_user_off',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'ШН'), ('groups__name', 'ШНС'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный ШН/ШНС при выключении'),
        ),
        migrations.CreateModel(
            name='JournalInspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_inspector_date_find', models.DateField(verbose_name='Дата выявления предотказного состояния')),
                ('journal_inspector_parameter', models.CharField(max_length=512, verbose_name='Параметр предотказного состояния')),
                ('journal_inspector_transferred', models.CharField(max_length=64, verbose_name='Передано')),
                ('journal_inspector_date_elimination', models.DateField(verbose_name='Устранить замечание до')),
                ('journal_inspector_date_finish', models.DateField(blank=True, null=True, verbose_name='Дата устранения замечания')),
                ('journal_inspector_сontrol_elimination', models.BooleanField(verbose_name='Контроль фактического устранения')),
                ('journal_inspector_responsible_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Ответсвенное предприятие')),
                ('journal_inspector_subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Место предотказного состояния')),
                ('journal_inspector_user_find', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выявил на месте')),
            ],
            options={
                'verbose_name': 'Замечания инспекторов',
                'verbose_name_plural': 'Замечание инспектора',
            },
        ),
    ]
