# Generated by Django 3.1.3 on 2020-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0020_auto_20201119_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalinspector',
            name='journal_inspector_сontrol_elimination',
        ),
        migrations.AddField(
            model_name='journalinspector',
            name='journal_inspector_control_elimination',
            field=models.BooleanField(default=False, verbose_name='Контроль фактического устранения'),
        ),
    ]
