# Generated by Django 3.1.3 on 2020-11-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0006_delete_contractor'),
        ('journals', '0021_auto_20201120_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalinspector',
            options={'verbose_name': 'Замечание инспектора', 'verbose_name_plural': 'Замечания инспекторов'},
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_emsu_friction_voltage_minus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при работе на фрикцию двигателя в минусовом положении, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_emsu_friction_voltage_plus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при работе на фрикцию двигателя в плюсовом положении, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_emsu_normal_voltage_minus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при нормальном переводе двигателя в минусовое положение, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_emsu_normal_voltage_plus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при нормальном переводе двигателя в плюсовое положение, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_emsu_translation_effort_minus',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Усилие перевода при работе на фрикцию, кгс(1кгс = 9.81 Ньютона в минусовом полождении)'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_emsu_translation_effort_plus',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Усилие перевода при работе на фрикцию, кгс(1кгс = 9.81 Ньютона в плюсовом положении)'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_msp_friction_voltage_minus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при работе на фрикцию двигателя в минусовом положении, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_msp_friction_voltage_plus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при работе на фрикцию двигателя в плюсовом положении, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_msp_normal_voltage_minus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при нормальном переводе двигателя в минусовое положение, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_msp_normal_voltage_plus',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Напряжение при нормальном переводе двигателя в плюсовое положение, В'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_power_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.amperagetype', verbose_name='Источник питания'),
        ),
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='journalemsu',
            name='journal_emsu_pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации записи'),
        ),
    ]
