# Generated by Django 3.1.3 on 2020-11-21 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('journals', '0022_auto_20201121_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalemsu',
            name='journal_emsu_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Станция'),
        ),
    ]
