# Generated by Django 3.1.3 on 2020-11-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
        ('journals', '0023_journalemsu_journal_emsu_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalcontractor',
            name='journal_contractor_subdivision',
        ),
        migrations.AddField(
            model_name='journalcontractor',
            name='journal_contractor_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Место проведения работ'),
        ),
    ]
