# Generated by Django 3.1.3 on 2020-11-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
        ('journals', '0024_auto_20201121_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalinspector',
            name='journal_inspector_subdivision',
        ),
        migrations.RemoveField(
            model_name='journalnotice',
            name='journal_notice_subdivision',
        ),
        migrations.RemoveField(
            model_name='journalorder',
            name='journal_order_object_subdivision',
        ),
        migrations.AddField(
            model_name='journalinspector',
            name='journal_inspector_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Место предотказного состояния'),
        ),
        migrations.AddField(
            model_name='journalnotice',
            name='journal_notice_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Место на предупреждение'),
        ),
        migrations.AddField(
            model_name='journalorder',
            name='journal_order_object_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Подразделение'),
        ),
    ]
