# Generated by Django 3.1.3 on 2020-11-25 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_contractor'),
        ('journals', '0025_auto_20201121_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifier_of_work', models.CharField(max_length=64, verbose_name='Классификтор')),
            ],
            options={
                'verbose_name': 'Классификторы работы',
                'verbose_name_plural': 'Классификтор работ',
            },
        ),
        migrations.CreateModel(
            name='JournalFactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_factory_date_start', models.DateTimeField(verbose_name='Начало периода')),
                ('journal_factory_date_finish', models.DateTimeField(verbose_name='Конец периода')),
                ('journal_factory_note', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('journal_factory_pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('journal_factory_classifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.classifierofwork', verbose_name='Классификация записи')),
                ('journal_factory_subdibision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.organization', verbose_name='Подразделение')),
                ('journal_factory_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ФИО сотрудника')),
            ],
            options={
                'verbose_name': 'Нахождение работников',
                'verbose_name_plural': 'Нахождения работников',
            },
        ),
    ]
