# Generated by Django 3.1.3 on 2020-11-25 08:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_contractor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0026_classifierofwork_journalfactory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalFactory',
            new_name='JournalFactoryOfWork',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_classifier',
            new_name='journal_factory_of_work_classifier',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_date_finish',
            new_name='journal_factory_of_work_date_finish',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_date_start',
            new_name='journal_factory_of_work_date_start',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_note',
            new_name='journal_factory_of_work_note',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_pub_date',
            new_name='journal_factory_of_work_pub_date',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_subdibision',
            new_name='journal_factory_of_work_subdibision',
        ),
        migrations.RenameField(
            model_name='journalfactoryofwork',
            old_name='journal_factory_user',
            new_name='journal_factory_of_work_user',
        ),
    ]
