# Generated by Django 3.1.3 on 2020-11-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subdivisions', '0006_delete_contractor'),
        ('journals', '0027_auto_20201125_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amperagetype',
            options={'verbose_name': 'Тип питания', 'verbose_name_plural': 'Типы питания'},
        ),
        migrations.AlterField(
            model_name='journalfactoryofwork',
            name='journal_factory_of_work_subdibision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subdivisions.subdivision', verbose_name='Подразделение'),
        ),
    ]
