# Generated by Django 3.1.3 on 2020-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0028_auto_20201127_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifierofwork',
            old_name='classifier_of_work',
            new_name='classifier_of_work_title',
        ),
        migrations.AddField(
            model_name='classifierofwork',
            name='classifier_of_work_short_title',
            field=models.CharField(max_length=64, null=True, verbose_name='Сокращенное название классификатора'),
        ),
    ]
