# Generated by Django 3.1.3 on 2020-12-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
        ('journals', '0029_auto_20201130_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalDisconnections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_disconnections_date', models.DateField(verbose_name='Дата отключения')),
                ('journal_disconnections_time_start', models.TimeField(verbose_name='Начало')),
                ('journal_disconnections_time_finish', models.TimeField(verbose_name='Кончало')),
                ('journal_disconnections_what_disconnected', models.CharField(max_length=256, verbose_name='Что отключается')),
                ('journal_disconnections_description', models.CharField(max_length=256, verbose_name='Опиасание')),
                ('journal_disconnections_time_staton', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Место')),
            ],
        ),
    ]
