# Generated by Django 3.1.3 on 2020-12-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
        ('journals', '0030_journaldisconnections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalDisconnections',
            new_name='JournalDisconnection',
        ),
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnections_date',
            new_name='journal_disconnection_date',
        ),
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnections_description',
            new_name='journal_disconnection_description',
        ),
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnections_time_finish',
            new_name='journal_disconnection_time_finish',
        ),
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnections_time_start',
            new_name='journal_disconnection_time_start',
        ),
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnections_time_staton',
            new_name='journal_disconnection_time_staton',
        ),
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnections_what_disconnected',
            new_name='journal_disconnection_what_disconnected',
        ),
    ]
