# Generated by Django 3.1.3 on 2020-12-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0031_auto_20201215_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journaldisconnection',
            old_name='journal_disconnection_time_staton',
            new_name='journal_disconnection_time_station',
        ),
    ]
