# Generated by Django 3.1.3 on 2020-12-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0032_auto_20201215_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaldisconnection',
            name='journal_disconnection_pub_date',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='journaldisconnection',
            name='journal_disconnection_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто опубликовал'),
        ),
    ]
