# Generated by Django 3.1.3 on 2020-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0033_auto_20201215_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaldisconnection',
            name='journal_disconnection_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Опиасание'),
        ),
    ]
