# Generated by Django 3.1.3 on 2020-12-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0034_auto_20201215_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaldisconnection',
            name='journal_disconnection_pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
