# Generated by Django 3.1.3 on 2020-12-15 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0035_auto_20201215_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaldisconnection',
            options={'verbose_name': 'Отлючение', 'verbose_name_plural': 'Отлючения'},
        ),
        migrations.CreateModel(
            name='JournalFireSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_fire_system_date', models.DateTimeField(verbose_name='Дата')),
                ('journal_fire_system_character', models.CharField(max_length=256, verbose_name='Характер неисправности')),
                ('journal_fire_system_reported', models.CharField(max_length=56, verbose_name='Сообщил')),
                ('journal_fire_system_datetime_fix', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('journal_fire_system_description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Примечание')),
                ('journal_fire_system_finished', models.BooleanField(verbose_name='Завершено')),
                ('journal_fire_system_confirmed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('journal_fire_system_reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Доложил об устранении')),
                ('journal_fire_system_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Замечание системы пожаротушения',
                'verbose_name_plural': 'Замечания систем пожаротушения',
            },
        ),
    ]
