# Generated by Django 3.1.3 on 2020-12-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0036_auto_20201216_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalfiresystem',
            name='journal_fire_system_pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='journaldisconnection',
            name='journal_disconnection_pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
