# Generated by Django 3.1.3 on 2020-12-16 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20201121_2258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0037_auto_20201216_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_cable_date_find', models.DateTimeField(verbose_name='Дата обнаружения')),
                ('journal_cable_place', models.CharField(max_length=256, verbose_name='Место укладки кабеля и длинна кабеля, м')),
                ('journal_cable_type', models.BooleanField(verbose_name='Кабель/Устройство')),
                ('journal_cable_brand', models.CharField(max_length=128, verbose_name='Марка и жильность кабеля')),
                ('journal_cable_om', models.FloatField(verbose_name='R изоляция (мОм)')),
                ('journal_cable_break', models.BooleanField(verbose_name='Обрыв')),
                ('journal_cable_description', models.CharField(max_length=256, verbose_name='Описание')),
                ('journal_cable_finish', models.BooleanField(verbose_name='Устранено')),
                ('journal_cable_date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата устранения')),
                ('journal_cable_measures', models.CharField(blank=True, max_length=128, null=True, verbose_name='Принятые меры')),
                ('journal_cable_pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('journal_cable_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.station', verbose_name='Станция/Перегон')),
                ('journal_cable_user', models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'ШН'), ('groups__name', 'ШНС'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Передал')),
            ],
            options={
                'verbose_name': 'Учет кабеля СЦБ',
                'verbose_name_plural': 'Учет кабелей СЦБ',
            },
        ),
    ]
