# Generated by Django 3.1.4 on 2021-02-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0038_journalcable'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalfactoryofwork',
            name='journal_factory_of_work_who_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
    ]
