# Generated by Django 3.1.4 on 2021-02-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0039_journalfactoryofwork_journal_factory_of_work_who_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalfactoryofwork',
            name='journal_factory_of_work_today',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
    ]
