# Generated by Django 3.1.3 on 2020-11-07 16:18

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20201106_2359'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='level',
            field=models.PositiveIntegerField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='lft',
            field=models.PositiveIntegerField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='rght',
            field=models.PositiveIntegerField(default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=False, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folder',
            name='organization',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация'),
        ),
    ]
