# Generated by Django 3.1.3 on 2020-11-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0007_auto_20201108_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
