# Generated by Django 3.1.3 on 2020-11-08 02:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0003_auto_20201106_2359'),
        ('organizations', '0002_auto_20201106_2359'),
        ('folders', '0008_auto_20201108_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_title', models.CharField(max_length=64, verbose_name='Наименование папки')),
                ('folder_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('folder_parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder', verbose_name='Родитесльская папка')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Организация')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Папки',
                'verbose_name_plural': 'Папка',
            },
        ),
    ]
