# Generated by Django 3.1.3 on 2020-11-08 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0009_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder_title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='folder',
            old_name='folder_parent',
            new_name='parent',
        ),
    ]
