# Generated by Django 3.1.3 on 2020-11-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0010_auto_20201108_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
    ]
