# Generated by Django 3.1.3 on 2020-11-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dgalist',
            options={'verbose_name': 'ДГА', 'verbose_name_plural': 'Списки ДГА'},
        ),
    ]
